# Generated by jeweler
# DO NOT EDIT THIS FILE
# Instead, edit Jeweler::Tasks in Rakefile, and run `rake gemspec`
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{redmine_plugin_support}
  s.version = "0.0.3"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Eric Davis"]
  s.date = %q{2009-11-07}
  s.description = %q{This libarary is a collection of rake tasks and other scripts that will make Redmine plugin development easier.}
  s.email = %q{edavis@littlestreamsoftware.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".gitignore",
     "CHANGES.rdoc",
     "History.txt",
     "LICENSE",
     "Manifest.txt",
     "PostInstall.txt",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "lib/redmine_plugin_support.rb",
     "lib/redmine_plugin_support/cucumber_task.rb",
     "lib/redmine_plugin_support/database_task.rb",
     "lib/redmine_plugin_support/environment_task.rb",
     "lib/redmine_plugin_support/general_task.rb",
     "lib/redmine_plugin_support/rdoc_task.rb",
     "lib/redmine_plugin_support/redmine_helper.rb",
     "lib/redmine_plugin_support/release_task.rb",
     "lib/redmine_plugin_support/rspec_task.rb",
     "lib/redmine_plugin_support/stats_task.rb",
     "lib/redmine_plugin_support/test_unit_task.rb",
     "redmine_plugin_support.gemspec",
     "script/console",
     "script/destroy",
     "script/generate",
     "tasks/rspec.rake",
     "test/redmine_plugin_support_test.rb",
     "test/test_helper.rb"
  ]
  s.homepage = %q{http://github.com/edavis10/redmine_plugin_support}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubyforge_project = %q{redmine_plugin_support}
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Libraries to automate the creation and management of Redmine plugins}
  s.test_files = [
    "test/test_helper.rb",
     "test/redmine_plugin_support_test.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<thoughtbot-shoulda>, [">= 0"])
    else
      s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
    end
  else
    s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
  end
end
